### ISSUE TITLE
Review google search console

### ISSUE THREAD

**Issue by roryrabbitfield** [theNewDynamic/oregonsadventurecoast.com#10]
Refresh Google Mobile-First Indexing: Client wants to make sure we have every base covered for Google.

_tND: Please comment about whether this is possible and give plan for implementing._

**Comment by regisphilibert** [comment]
@budparr do we have something in place? Do you have access?

**Comment by budparr** [comment]
no. You have to just add it add yourself to the site.

**Comment by regisphilibert** [comment]
We have serveral errors on mobile

Small texts (easily addressed)
Element larger than screen (horizontal scroll). This could be easy or hard depending on a lot of stuff.
Clickable elements too close to each other. This one I'm not sure how to identify. I don't know how to see which elements are affected.

@budparr I'm not sure how to make you access that search console dashboard?

**Comment by budparr** [comment]
I can access it if I need to. I think these are just things that we need to report back to Tim, isn’t that right?

**Comment by budparr** [comment]
I've created an Epic with the issues that Google is reporting. They will need to be addressed with the client:

https://zube.io/the-new-dynamic/team-1/epics/7
