### ISSUE TITLE
Investigate Tim's LAMP Question

### ISSUE THREAD

**Issue by regisphilibert** [theNewDynamic/oregonsadventurecoast.com#113]
We have a change with the state travel organization (Travel Oregon) and their database (OTIS) that we pull our calendar data from. 

Travel Oregon is required (because of the lockdown) to remove all things flagged “Events” on their website / database because technically, Events are not allowed right now. However, the Coos Bay Farmer’s Market is opening back up with appropriate social distancing. Travel Oregon is changing the designation of all Farmer’s Markets from being lumped in with all other “Events" to “Farmers Markets”. 

What would it take to include 'Farmers Markets’ in the OTIS API pull request for the Calendar page?

**Comment by AdamChlan** [comment]
@regisphilibert it looks like the endpoints are controlled in the config.php file. It seems like we may have a couple options.  

1.Create a new endpoint in config.php for Farmers Markets.
2. Change the logic on the Events page to only show events designated as farmers markets. I'll need to take a look at how this event page is being populated in the Hugo site.

A few questions..

1. Do we have access to the OTIS admin area to see if #2 is possible?
2. Is there a staging API and staging area we can test any changes, or do we need to do it live?

**Comment by regisphilibert** [comment]
Client is inquiring and will bet back to us.

**Comment by regisphilibert** [comment]
Here are the login, sorry about the delay @AdamChlan.

Here is the link: https://otis.traveloregon.com/api/v4/
 
Browser login:
un: orbuser
pw: testing
 
API login:
un: API_OAC_EchoCreative
pw: OTISechoAPI

**Comment by AdamChlan** [comment]
@regisphilibert I took a look at the admin area. This seems to be a way to view the endpoints and drill down on the data. I also assume this is the live API and there is no staging API to do tests with. 

I suppose we could try to add a new dataType as seen in config.php, and see if that gets us anywhere.

Here's what I assume is the existing code that the calendar uses:

    "calendar" => array(
        "endpoint" => "listings/?city=Coos Bay|North Bend|Charleston&type=Events",
        "file" => "calendar.json",
    ),

perhaps we set up a new endpoint of

    "farmersmarkets" => array(
        "endpoint" => "listings/?city=Coos Bay|North Bend|Charleston&type=FarmersMarkets",
        "file" => "farmersmarkets.json",
    ),

I don't know how the json files are generated so I don't know if farmersmarket.json is a file that would be produced by they system or not.

**Comment by regisphilibert** [comment]
Thanks @AdamChlan is there a way to have one endpoint list several types? It seems to be possible using `|` for the `city` parameter, so maybe with `type` as well?

This way we woudn't have too much to adjust I think:

```
"calendar" => array(
    "endpoint" => "listings/?city=Coos Bay|North Bend|Charleston&type=Events|FarmersMarkets",
    "file" => "calendar.json",
),
```

**Comment by AdamChlan** [comment]
I thought about that as well. I suppose that would be a good option if they were not going to add any events, or mark them as drafts...basically whatever it takes to not have them show.

**Comment by AdamChlan** [comment]
I think we would need to confirm what that Farmers Market slug will be

**Comment by regisphilibert** [comment]
Ok just to sum up what we found with @AdamChlan looking at the API dashboard.

We can retrieve both Events and Farmers Markets using `https://otis.traveloregon.com/api/v4/listings/?city=Coos%20Bay|North%20Bend|Charleston&type=Events|Farmers%20Markets` endpoint.

This would mean only updating the calendar option in the PHP script to include `Farmers Markets`. I'll ask confirmation with client and we can try and proceed.

@AdamChlan could quickly try and see if you can try to run the script on your machine? I think all it needs is a basic MAMP environment to run but...

**Comment by AdamChlan** [comment]
@regisphilibert I was not able to get this running locally. It's not able to resolve the /api/v4/ aspect of the URL, so I can't log in or try to hit that endpoint URL locally. Does that directory exist somewhere on Media Temple?

**Comment by AdamChlan** [comment]
@regisphilibert seems like we are good to close this on out?

**Comment by regisphilibert** [comment]
Client had not confirmed but just did! Thanks!
