### ISSUE TITLE
Check API script work with PHP 7.3

### ISSUE THREAD

**Issue by regisphilibert** [theNewDynamic/oregonsadventurecoast.com#117]
Got an email form MediaTemple which warns of future default update to PHP 7.3.

- [ ] Check if data-api php code works with PHP 7.3
- [ ] Perform any light update to code to make it comply with 7.3
- [ ] If too much work, set "Legacy" option and advise. We'll have until september 30 to decide what to do.

[Attached email](https://github.com/theNewDynamic/oregonsadventurecoast.com/files/4754219/Important.Notice.Regarding.Your.Grid.Service.pdf)

**Comment by AdamChlan** [comment]
@regisphilibert as a first test, I ran all the code through a PHP compatibility tool for PHP 7.3, and no issues were found, so that is a good sign. I'll do more testing locally, to see if I get any PHP errors logged while under 7.3.

**Comment by AdamChlan** [comment]
@regisphilibert I am not seeing PHP deprecation errors when hitting the site locally. That said, I have not really achieved getting the site running as it does on production. I can get to the admin page, and hit the script links. There are no PHP7 errors when I do that.

I wonder if we'd be able to upgrade to 7.3, confirm, and if any issues, fall back to legacy. I can engage with Media Temple to see if that is an option.

**Comment by regisphilibert** [comment]
> I wonder if we'd be able to upgrade to 7.3, confirm, and if any issues, fall back to legacy. I can engage with Media Temple to see if that is an option.

That would be ideal @AdamChlan . Do you need the creds again?

**Comment by AdamChlan** [comment]
No I have them

**Comment by AdamChlan** [comment]
@regisphilibert they confirmed we'd be able to switch back. I suppose we'd update to 7.3, makes sure we can access the admin area. Then consider running the script manually...or wait for the cron to run. Then confirm in the AM...check logs, site data, etc.

**Comment by regisphilibert** [comment]
That's awesome, we can wait for the cron to run. 

Could you set up a reminder to check the logs every day for one week? Unless by looking at the code, you can tell every part of the scripts will be ran every day.

I just want to make sure, one function is not ran because say, there's no new entry that day, and the function eventually is ran and breaks in two weeks when we're not looking anymore.

**Comment by AdamChlan** [comment]
yes makes sense. do we want to make the change today?

**Comment by regisphilibert** [comment]
> do we want to make the change today?

Sure, why not.

**Comment by AdamChlan** [comment]
Okay it's been updated. I hit the main admin page, and it loads, and no errors in logs. I'll check from here on out, like discussed above.

**Comment by AdamChlan** [comment]
@regisphilibert just confirming that logs are looking free of any php error since upgrading

**Comment by regisphilibert** [comment]
Awesome, let's wait for friday (that'll complete one full week of monitoring) and close this.
