### ISSUE TITLE
Add category to Shopping

### ISSUE THREAD

**Issue by budparr** [theNewDynamic/oregonsadventurecoast.com#125]
From Tim:

>We need to add an additional category to Shopping, please:

> Pet Products

**Comment by budparr** [comment]
@regisphilibert Maybe you did this?

**Comment by regisphilibert** [comment]
Or not... :(

**Comment by regisphilibert** [comment]
I will.

**Comment by budparr** [comment]
are you going to reply to Tim, or would you like me to?

**Comment by regisphilibert** [comment]
Just did.
