### ISSUE TITLE
Generate a list of blog categories used on the site

### ISSUE THREAD

**Issue by budparr** [theNewDynamic/oregonsadventurecoast.com#127]
Tim would like to list all of the categories used in blog posts on the site. 

> list of all the blog categories currently used on the site

<details><summary>Full request (this is # 4)</summary>

Our blog writer is wanting to go through the blogs and fix the blog categories. She has been running roughshod adding all different versions and using random words for quite a while.

We know she can go through the blog posts one by one and edit, but we have a question about the capabilities allowed for editing the Git - or maybe a suggestion for another option. And btw, we are not looking to do this ourselves. 

Question:

1) Are you able to do a search and replace throughout all the blogs?
So for example, we would want all instances of a specific category replaced.

Like: ‘- Highway Trips’, replaced with ‘- Road Trips'

2) If you could do this search and replace, would you be able to remove (delete) instances too?
For example, we might have a number of random categories that can just be removed all together. 

3) If this is possible, would the search and replace be case sensitive? It’s likely there are probably both ‘- Jumping Beans’ and ‘- jumping beans’. 

4) Would there be a way for you to provide us with a list of all the blog categories currently used on the site?

I imagine we would provide  you with a spreadsheet of the specific category and the action (delete or replace). 

</details>

**Comment by regisphilibert** [comment]
I'm going to close this. We'll create issues if search/replace is mandated.
