### ISSUE TITLE
Add Video to Home Page Slider 

### ISSUE THREAD

**Issue by roryrabbitfield** [theNewDynamic/oregonsadventurecoast.com#15]
Create an option to easily add a video to the home page slider.

We need to switch to Flickity to handle the homepage carousel, and add videos to it. Flickity has events fired on many events such as next slide etc... So we could easily pause/resume videos.

I think the safest route is to use HTML5 videos as it will allow us to autoplay most conviniently, this PR theNewDynamic/oregonsadventurecoast.com#55 can be used as inspiration (especially this [file](https://github.com/theNewDynamic/oregonsadventurecoast.com/blob/415d8bbc3342f8c1e01fee626e08cda8cd63ebb4/layouts/partials/video-test.html)) but not a starter.

**Comment by roryrabbitfield** [comment]
More info from [Tim's spreadsheet](https://docs.google.com/spreadsheets/d/1kuvM5PjaS_40YwfVyVXopCW3zkhQXKOUoLtxrnVOIJg/edit#gid=1677824091):

We will need the quote for the home page slider to allow for Video (and it should scale appropriately for different devices) and Static Photo Slides.

"1) The Video should scale appropriately for different devices and ?? should it be suppressed for mobile? 

2) We want to have additional static photo slides that we can (a) Put text over the picture; (b) include a separate (like learn more) button; and (c) have the ability to add a link to the large photo. We won't need complex animation for the text or button, but something simple where they slide in would be great. 

3) We still want to have the separate option for the mobile photo to replace the slider if user is on mobile device. 

4) If any of the specifics I've listed here make this complicated (or really expensive) I'm open to reducing my wish list. I'm used to working with the Layer Sliders from Wordpress which allow for a lot of functionality. "

**Comment by roryrabbitfield** [comment]
Rory to check if Tim approved this to go forward

**Comment by roryrabbitfield** [comment]
this is approved  by Tim to go forward

**Comment by regisphilibert** [comment]
I just created a PR (#55)as part of my investigations. Turns our simply adding an HTML video tag is the fastest route. Though I'm not sure autoplays works.
I also added a Youtube iframe and a Vimeo iframe, but both requires the user the click in order for the video to start even with the `autoplay` argument. It might be because the slide is hidden on init....

**Comment by regisphilibert** [comment]
@budparr I think the safest route is to use our own hosted Video files with <video> HTML. We can host it anywhere, but what we cannot easily do is use a service like Vimeo or Youtube.

I think it's fairly safe to use MP4 (H.264) as it is now supported by every browser.

Now this solution means the client will be responsible for encoding the videos.

This completes my investigation. We should report to Tim and advise.

**Comment by regisphilibert** [comment]
Pending theNewDynamic/oregonsadventurecoast.com#63

**Comment by regisphilibert** [comment]
@roryrabbitfield Tim mentioned he wanted a hyperlink on the image/video. Must have skipped our spec. @mountainbug95 I don't think this is a big deal, but shout if it is.
