### ISSUE TITLE
Make phone number clickable throughout site

### ISSUE THREAD

**Issue by regisphilibert** [theNewDynamic/oregonsadventurecoast.com#161]
> Our SEO/SEM people asked if we could get some of the phone numbers clickable on the mobile. I looked through and found that most everything that is included in regular copy on the page - the phone numbers are hot. We noticed thought that anything that’s included dynamically (like the Lodging Properties, Dining, Equipment Rental, Tour Guide & Charters, Events and Calendar) are not hot. 

> Is there a way to make these listings have hot phone numbers? My SEO team suggested just adding an <a href> but I’m not sure that is best practice. Either way - it would help us track people calling the businesses from the website directly.

**Comment by regisphilibert** [comment]
@AdamChlan we need to spec a bit and maybe review the project you and I. I think you had worked on it in the past but it might be a long time ago.

**Comment by AdamChlan** [comment]
@regisphilibert yes, I am familiar enough with the project. I can investigate the areas they mention, or let me know if you want to chat.

**Comment by regisphilibert** [comment]
I don't need to chat. Do let me know if you have any questions of course.
