### ISSUE TITLE
Update HP graphic

### ISSUE THREAD

**Issue by budparr** [theNewDynamic/oregonsadventurecoast.com#165]
> The client has signed up for this survey again and wants to add it back to the home page. 

> Please add it below the masonry links (like in the screen shot attached) and use the following link (making sure to open it in a new window). We would like it to just resize for tablet/mobile. 

> LINK: https://craterlakecountry.com/coos-bay/

![win-500-fill-out-survery](https://user-images.githubusercontent.com/115347/106162499-2e7da500-6156-11eb-8357-7dff2e1666bd.png)
![Win-Survey-Placement](https://user-images.githubusercontent.com/115347/106162501-2e7da500-6156-11eb-918a-a9d72c55013d.jpg)

**Comment by regisphilibert** [comment]
Thanks @budparr!
