### ISSUE TITLE
Add Spanish Homepage / Keep site monolingual for now

### ISSUE THREAD

**Issue by regisphilibert** [theNewDynamic/oregonsadventurecoast.com#189]
1) Navigation Header (Leave this in English)

2) We will have a single image in the slider (Probably want the slider functionality where we can include a mobile image as well)

3) Visitor Guide Text and PDF in English Ok

4) Main Headline and Copy: We will be translating new copy here.

5) We will be replacing the little Hero image with a new image and translated Text

6) Masonry Area - We can leave this exactly as it is in English.

7) REMOVE Blog articles/feed. We won’t want the blog articles on this page.

8) Footer in English is OK

9) Is there some sort of designation in the head where you define the language? Something maybe Google looks at? Not sure if this would mess things up (with leaving the English on there). Thoughts?

[SpanishHomePage-03.pdf](https://github.com/theNewDynamic/oregonsadventurecoast.com/files/6670557/SpanishHomePage-03.pdf)

**Comment by budparr** [comment]
seems like this is something we should price out hours on.

**Comment by regisphilibert** [comment]
Yes I added so it's on our radar

**Comment by budparr** [comment]
Tim is asking about this issue, @regisphilibert For some reason I thought we were waiting on him for more assets?

**Comment by regisphilibert** [comment]
We are waiting for assets for 2. 4. and 5. did we get them?

**Comment by budparr** [comment]
Not that I know of. Can you just respond to the email from today? Perhaps he forgot

**Comment by budparr** [comment]
> Here is the translation for the Title:
> Planifique sus vacaciones | En Oregon costa de aventuras
