### ISSUE TITLE
Review page load performance

### ISSUE THREAD

**Issue by budparr** [theNewDynamic/oregonsadventurecoast.com#196]
We have a couple issues we’re noticing with loading time on the website. Specifically, the Lodging Page and the Dining page. On the default view, they are each taking around 30 seconds to load. Can you guys look into this?

**Comment by regisphilibert** [comment]
This is the culprit: https://dni.trumeasure.com/Scripts/TMLoader.js

Scripts holds while ☝️ remains pending, and is finally released once ☝️ fails to load for good.

**Comment by regisphilibert** [comment]
Client has removed the failing script.
