### ISSUE TITLE
[AUG 6] Meili: Move indexes from cloud.meilisearch to our self hosted server

### ISSUE THREAD

**Issue by regisphilibert** [theNewDynamic/oregonsadventurecoast.com#237]
There's three indexes to move (and port settings)
- dining
- lodging
- shopping

**Comment by budparr** [comment]
Updated this to reflect that 8/6 is the Mieli cutoff

**Comment by regisphilibert** [comment]
Ah here comes the rub... We're using Meili 0.20.0 on our search.tnd.dev... It seems I cannot simply use the same settings... Keys have changed etc... In other words the database are not compatible... 

Of course their documentation is not archived for each version... so no way to know how we're supposed to convert this old settings to new ones... At least I was not able to do so.

I think the faster route is the update our current meili install to .28 and make sure ndbooks is functionnal.
