### ISSUE TITLE
investigate slow performance

### ISSUE THREAD

**Issue by roryrabbitfield** [theNewDynamic/oregonsadventurecoast.com#46]
Tim writes:

> I was working on the site today (Sunday, Sept 15, 2019) and the site was taking a long time to load (15 to 30 seconds on the home page)
> 
> A few times I got a 503 Error. I'm not sure what's happening, but we've never seen this before when we were sitting in regular hosting. We have a ton of Advertising, Web Ads, Google Ads & Retargeting dropping and we can't have the site stalling. Is there anything to eliminate this?
>

**Comment by tm-const** [comment]
Optimize your images - most of the images take 1s to load (**See attached**). This may be an issue if your server does not have enough resources per day. If you cap on resource usage on your server - the speed of the website may be effected by this until you restart your server.

Optimize your images and check with your hosting provider about increasing resource cap on your server.

![Screen Shot 2019-09-20 at 11 12 09 AM](https://user-images.githubusercontent.com/55524897/65338117-8508c580-db97-11e9-9423-25cfa8b466da.png)

**Comment by budparr** [comment]
I've done a performance review and there are some items we can fix that will have a big impact on the site. I've outlined them in a ticket so we can estimate and get approval on before making issues for them.
