### ISSUE TITLE
Investigate Serach bug

### ISSUE THREAD

**Issue by budparr** [theNewDynamic/oregonsadventurecoast.com#48]
It appears that the search script (lunr.js) is not loading, thus search renders no results. I think if we make sure that script is being rendered and available to the site, it will fix it.

https://www.oregonsadventurecoast.com/search/?search=coast

**Comment by budparr** [comment]
![Screenshot 2019-10-16 10.20.27.jpg](https://zube.io/files/the-new-dynamic/f2010fc2fa24c0cee9385799be8b7584-screenshot-2019-10-16-10-20-27.jpg)

**Comment by budparr** [comment]
Looking at this issue, my guess is that Lunr and Jquery are not loading in the proper order (they are set to defer even though they're in the footer). I'm having a hard time manipulating the scripts. @AdamChlan do you have time to fool around with this today?

**Comment by AdamChlan** [comment]
yes, I was trying to hunt down the issue yesterday but didn't have luck. This note is helpful. Will let you know what I find.

**Comment by AdamChlan** [comment]
I'm not seeing lunr.json in the site at all. Is this the main problem we are dealing with? We have no index?

**Comment by budparr** [comment]
its being called in search.js

**Comment by regisphilibert** [comment]
Is the old repo available somewhere? We need to identify what function created this lunr.js file.

**Comment by AdamChlan** [comment]
Looks like here:

https://github.com/echopdx/coosbay/tree/master/tools

Will see if I can come up with anything.

**Comment by budparr** [comment]
great! if its not looking like a relatively quick fix, we can come back to it later.
