### ISSUE TITLE
Fix sidebar links on Trip Ideas pages (links do not return correct info)

### ISSUE THREAD

**Issue by roryrabbitfield** [theNewDynamic/oregonsadventurecoast.com#61]
https://www.oregonsadventurecoast.com/tripideas/

Tim came across a problem on the Trip Ideas page(s). There is a sidebar with breakouts (like a blog with categories and tags) with “Duration”, “Towns” and “Adventures”. 

When you click one of the links under those categories, they are supposed to return (as an example) all the Full Day durations. But Tim discovered that the Towns - is linking back to the Our Area pages - not returning the list of all the Trip Ideas in a particular town.

**Comment by regisphilibert** [comment]
> Hi Tim, 
>
> this is setup in the redirects:
>
> /towns/north-bend                                       /our-area-north-bend
> /towns/coos-bay                                         /our-area-coos-bay
> /towns/charleston                                       /our-area-charleston
>
> This is what trigger the behaviour. /towns/north-bend is pointing the town Taxonomy but is intercepted by the redirect.
>
> Should we remove those redirects?

**Comment by regisphilibert** [comment]
Taken care of by https://github.com/theNewDynamic/oregonsadventurecoast.com/commit/6a8adcf8c7ad8ac82aea32d3f28761b502af16e8
