### ISSUE TITLE
Estimate performance work for Tim (from ticket)

### ISSUE THREAD

**Issue by roryrabbitfield** [theNewDynamic/oregonsadventurecoast.com#76]
#### [Ticket #17: **Estimate performance work for Tim**](https://zube.io/the-new-dynamic/team-1/tickets/17)

Reviewing performance in [#1059      (theNewDynamic/oregonsadventurecoast.com#46)](https://zube.io/the-new-dynamic/team-1/c/1059) 

I've come up with a few items we can do, but we should estimate for Tim:

- [ ] use imgix for serving images
- [ ] optimize image size and format where possible
- [ ] Implement lazyloading: https://github.com/aFarkas/lazysizes

- [ ] Reduce number of items in HP carousel

**Comment by regisphilibert** [comment]
I estimate the following:

#### Use imgix for serving image + optimize image size and format when possible 👉  3.5 hours
We need to
1. Update Hugo
2. Use imgix module
3. Search in the code where images are referenced and apply correct imgix partial plus sensible transformations.

#### Implement layzloading 👉  2 hours

#### Reduce number of items in HP carousel 👉  .5 hours
