### ISSUE TITLE
Review Forestry deleting layout

### ISSUE THREAD

**Issue by budparr** [theNewDynamic/oregonsadventurecoast.com#98]
The dining page lost its layout in production. Here's the commit https://github.com/theNewDynamic/oregonsadventurecoast.com/commit/47aa2dc58e2236d2b1a8083c0dfa6785dda920c5

**Comment by regisphilibert** [comment]
I would guess the previously assigned layout was not in the list of options available to the editor through the select field. Therefor Forestry would ignore the current value on the front end and present the layout select field with no option selected. Upon saving a change Forestry passes an empty value for the layout field through the “ form data” and the backend overwrites previous value with an empty string.

**Comment by budparr** [comment]
Okay. Can close this?
